server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello
          uri: http://httpbin.org
          predicates:
            - Path=/post
          filters:
            - AddRequestHeader=X-Request-Hello, PostWold